package chain

import (
	"context"
	"fmt"
	"math/big"
	"strings"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/ethereum/go-ethereum/rpc"

	"github.com/lancechuangdev/prism/backend/internal/contracts"
)

type RPCReader struct {
	client  *ethclient.Client
	pool    *contracts.PrismPoolCaller
	chainID string
}

func NewRPCReader(ctx context.Context, rpcURL string, poolAddress string) (*RPCReader, error) {
	if strings.TrimSpace(rpcURL) == "" {
		return nil, fmt.Errorf("RPC URL is required")
	}
	if !common.IsHexAddress(poolAddress) {
		return nil, fmt.Errorf("invalid PrismPool address %q", poolAddress)
	}

	client, err := ethclient.DialContext(ctx, rpcURL)
	if err != nil {
		return nil, fmt.Errorf("connect chain RPC: %w", err)
	}
	return newRPCReader(ctx, client, poolAddress)
}

// Constructor for Production
func newRPCReader(ctx context.Context, client *ethclient.Client, poolAddress string) (*RPCReader, error) {
	chainID, err := client.ChainID(ctx)
	if err != nil {
		client.Close()
		return nil, fmt.Errorf("read RPC chain ID: %w", err)
	}
	// PrismPoolCaller is the read-only Go wrapper generated by abigen for the deployed PrismPool contract.
	pool, err := contracts.NewPrismPoolCaller(common.HexToAddress(poolAddress), client)
	if err != nil {
		client.Close()
		return nil, fmt.Errorf("bind PrismPool: %w", err)
	}

	return &RPCReader{
		client:  client,
		pool:    pool,
		chainID: chainID.String(),
	}, nil
}

// Constructor for Tests
func newInProcessRPCReader(ctx context.Context, rpcClient *rpc.Client, poolAddress string) (*RPCReader, error) {
	return newRPCReader(ctx, ethclient.NewClient(rpcClient), poolAddress)
}

func (r *RPCReader) Close() {
	r.client.Close()
}

func (r *RPCReader) PoolLength(ctx context.Context, chainID string) (int64, error) {
	if err := r.validateChainID(chainID); err != nil {
		return 0, err
	}
	count, err := r.pool.PoolCount(&bind.CallOpts{Context: ctx})
	if err != nil {
		return 0, fmt.Errorf("call poolCount: %w", err)
	}
	if !count.IsInt64() {
		return 0, fmt.Errorf("pool count %s exceeds int64", count)
	}
	return count.Int64(), nil
}

func (r *RPCReader) PoolBaseInfo(ctx context.Context, chainID string, contractIndex int64) (ContractPoolBase, error) {
	if err := r.validateIndex(chainID, contractIndex); err != nil {
		return ContractPoolBase{}, err
	}
	pool, err := r.pool.GetPool(&bind.CallOpts{Context: ctx}, big.NewInt(contractIndex))
	if err != nil {
		return ContractPoolBase{}, fmt.Errorf("call getPool(%d): %w", contractIndex, err)
	}
	return ContractPoolBase{
		SettleTime: pool.SettleTime.String(), EndTime: pool.MaturityTime.String(),
		InterestRate: pool.InterestRate.String(), MaxSupply: pool.MaxLendSupply.String(),
		LendSupply: pool.TotalLendDeposited.String(), BorrowSupply: pool.TotalCollateralDeposited.String(),
		MortgageRate: pool.CollateralizationRatio.String(), LendTokenAddress: pool.LendToken.Hex(),
		BorrowTokenAddress: pool.CollateralToken.Hex(), State: fmt.Sprint(pool.State),
		SPCoin: pool.LenderPositionToken.Hex(), JPCoin: pool.BorrowerPositionToken.Hex(),
		AutoLiquidateThreshold: pool.LiquidateRate.String(),
	}, nil
}

func (r *RPCReader) PoolDataInfo(ctx context.Context, chainID string, contractIndex int64) (ContractPoolData, error) {
	if err := r.validateIndex(chainID, contractIndex); err != nil {
		return ContractPoolData{}, err
	}
	data, err := r.pool.GetPoolData(&bind.CallOpts{Context: ctx}, big.NewInt(contractIndex))
	if err != nil {
		return ContractPoolData{}, fmt.Errorf("call getPoolData(%d): %w", contractIndex, err)
	}
	return ContractPoolData{
		SettleAmountLend: data.SettleAmountLend.String(), SettleAmountBorrow: data.SettleAmountBorrow.String(),
		FinishAmountLend: data.FinishAmountLend.String(), FinishAmountBorrow: data.FinishAmountBorrow.String(),
		LiquidationAmountLend:   data.LiquidationAmountLend.String(),
		LiquidationAmountBorrow: data.LiquidationAmountBorrow.String(),
	}, nil
}

func (r *RPCReader) TokenInfo(ctx context.Context, chainID string, tokenAddress string) (ContractToken, error) {
	if err := r.validateChainID(chainID); err != nil {
		return ContractToken{}, err
	}
	if !common.IsHexAddress(tokenAddress) {
		return ContractToken{}, fmt.Errorf("invalid token address %q", tokenAddress)
	}
	address := common.HexToAddress(tokenAddress)
	token, err := contracts.NewERC20TokenCaller(address, r.client)
	if err != nil {
		return ContractToken{}, fmt.Errorf("bind ERC-20 token %s: %w", address.Hex(), err)
	}
	symbol, err := token.Symbol(&bind.CallOpts{Context: ctx})
	if err != nil {
		return ContractToken{}, fmt.Errorf("call symbol on %s: %w", address.Hex(), err)
	}
	decimals, err := token.Decimals(&bind.CallOpts{Context: ctx})
	if err != nil {
		return ContractToken{}, fmt.Errorf("call decimals on %s: %w", address.Hex(), err)
	}
	return ContractToken{Address: address.Hex(), Symbol: symbol, Decimals: int(decimals)}, nil
}

func (r *RPCReader) validateIndex(chainID string, contractIndex int64) error {
	if err := r.validateChainID(chainID); err != nil {
		return err
	}
	if contractIndex < 0 {
		return fmt.Errorf("contract index must not be negative")
	}
	return nil
}

func (r *RPCReader) validateChainID(chainID string) error {
	if chainID != r.chainID {
		return fmt.Errorf("reader connected to chain %s, requested chain %s", r.chainID, chainID)
	}
	return nil
}
